spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.38.36:3306/sea?characterEncoding=utf-8&SSL=false
    username: zqzq
    password: Zq123456!
  jpa:
    show-sql: true
  redis:
    host: 101.200.38.36
    port: 6379
server:
  servlet:
    context-path: /sea
